### PR TITLE
fix on edit debates dates not saving correctly

### PR DESCRIPTION
**Pull request by spuigmitjadxc**
#### :tophat: What? Why?

fix on dates when edit debates, error "can not be blank" given when date was not blank and not edited

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [ ] Add `CHANGELOG` entry
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
Description

### CODE REVIEW

**Comment by tramuntanal** [comment]
Hi @spuigmitjadxc ,
I understand that the problem is `"field can not be blank" error given when was not blank and not edited`.

I would like to find the cause of the problem and not an override patch. We're going to have to deal with this override forever. Can you dig a little bit?

**Comment by spuigmitjadxc** [comment]
Hi @tramuntanal ,
Dug in it and I see that error is the cause of a bad formatting when setting the saved datetime on form date picker, but when changed from date picker have the correct format, didn't find another way to patch it

**Comment by Leusev** [comment]
Hi @spuigmitjadxc 
I cloned the repo and switched to v0.21 as well as dependant Decidim repo in order to reproduce the bug, but I couldn't.
Could you kindly add some more info or tell following steps to reproduce it please?
Thanks in advance!

**Comment by spuigmitjadxc** [comment]
Hi @Leusev,
When editing some date from Debats from an existing Debat it sets the other date as blank field, but it is actually displayed with wrong format, so for that reason it just throws an error from blank field when trying to save the changes

**Comment by Leusev** [comment]
Hi @spuigmitjadxc 
this solution could cause an error if one or both of start/end debate's attributes are empty, when it tries to format them: 
image
In this case, I've looked for another solution that maybe it could fix on other way. I created another PR #165  
// cc @tramuntanal

**Comment by spuigmitjadxc** [comment]
Hi @Leusev ,

Ok, thank you, then I procced to close this pull request,

Solution in #165

**Pull request closed without merging**
